### ISSUE TITLE
Unable to create a driver for GCE

### ISSUE THREAD

**Issue by g-awmalik** [apache/libcloud#1355]
## Summary

While running gce_demo.py, I always get the this exception:

File "/Users/awmalik/Library/Python/2.7/lib/python/site-packages/libcloud/common/google.py", line 483, in __init__
    raise GoogleAuthError('cryptography library required for '
libcloud.common.google.GoogleAuthError: 'cryptography library required for Service Account Authentication.'

## Detailed Information

Here's the full stacktrace for the exception when I try to run gce_demo.py

Traceback (most recent call last):
  File "gce_demo.py", line 958, in <module>
    main_compute()
  File "gce_demo.py", line 343, in main_compute
    gce = get_gce_driver()
  File "gce_demo.py", line 112, in get_gce_driver
    driver = get_driver(Provider.GCE)(*args, **kwargs)
  File "/Users/awmalik/Library/Python/2.7/lib/python/site-packages/libcloud/compute/drivers/gce.py", line 1886, in __init__
    super(GCENodeDriver, self).__init__(user_id, key, **kwargs)
  File "/Users/awmalik/Library/Python/2.7/lib/python/site-packages/libcloud/common/base.py", line 976, in __init__
    self.connection = self.connectionCls(*args, **conn_kwargs)
  File "/Users/awmalik/Library/Python/2.7/lib/python/site-packages/libcloud/compute/drivers/gce.py", line 99, in __init__
    credential_file=credential_file, **kwargs)
  File "/Users/awmalik/Library/Python/2.7/lib/python/site-packages/libcloud/common/google.py", line 772, in __init__
    user_id, key, auth_type, credential_file, scopes, **kwargs)
  File "/Users/awmalik/Library/Python/2.7/lib/python/site-packages/libcloud/common/google.py", line 660, in __init__
    self.user_id, self.key, self.scopes, **kwargs)
  File "/Users/awmalik/Library/Python/2.7/lib/python/site-packages/libcloud/common/google.py", line 483, in __init__
    raise GoogleAuthError('cryptography library required for '
libcloud.common.google.GoogleAuthError: 'cryptography library required for Service Account Authentication.'

Python version: Python 2.7.10
Libcloud version: apache_libcloud-2.6.0.dist-info
PyCrypto version: pycrypto-2.6.1.dist-info

**Comment by g-awmalik** [comment]
Resolved it by installing the following package:

pip install --user cryptography
