### ISSUE TITLE
Can no longer get driver by provider name string

### ISSUE THREAD

**Issue by dpeschman** [apache/libcloud#1390]
## Summary

Can no longer get driver by provider name string as of 2.7.0.

## Detailed Information

```bash
home@billy [~]--[$ python3 -m venv libcloud-venv
home@billy [~]--[$ . libcloud-venv/bin/activate
(libcloud-venv) home@billy [~]--[$ pip install apache-libcloud==2.7.0
...
Successfully installed apache-libcloud-2.7.0 certifi-2019.11.28 chardet-3.0.4 enum34-1.1.6 idna-2.8 requests-2.22.0 typing-3.7.4.1 urllib3-1.25.7
(libcloud-venv) home@billy [~]--[$ python
Python 3.7.5 (default, Nov  1 2019, 02:16:32)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from libcloud.compute.providers import get_driver
>>> get_driver('openstack')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/billy/libcloud-venv/lib/python3.7/site-packages/libcloud/compute/providers.py", line 178, in get_driver
    deprecated_constants=deprecated_constants)
  File "/Users/billy/libcloud-venv/lib/python3.7/site-packages/libcloud/common/providers.py", line 73, in get_driver
    raise AttributeError('Provider %s does not exist' % (provider))
AttributeError: Provider openstack does not exist
```

Works in 2.6.0:
```bash
(libcloud-venv) home@billy [~]--[$ pip install -U 'apache-libcloud==2.6.0'
...
Successfully installed apache-libcloud-2.6.0
(libcloud-venv) home@billy [~]--[$ python
Python 3.7.5 (default, Nov  1 2019, 02:16:32)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from libcloud.compute.providers import get_driver
>>> get_driver('openstack')
<class 'libcloud.compute.drivers.openstack.OpenStackNodeDriver'>
```

Not sure if this is a bug, or if we've just been using it wrong.

**Comment by Kami** [comment]
Thanks for reporting this.

It's likely related to recent MyPy refactoring.

Getting driver class reference using a string and not a constant was never really an officially supported and documentation approach (iirc), but if it worked in older releases it should still probably be considered as a bug (at least for a couple of major releases)).

In the mean time, the recommend approach and a workaround is to use ``libcloud.compute.types.Provider.OPENSTACK`` constant.

**Comment by Kami** [comment]
#1391 should fix it.

Thanks again for reporting this.

**Comment by dpeschman** [comment]
The backstory on why we use strings is, we have a couple custom drivers for talking to in-house APIs, and those we have to load by string since they aren't in the enum.
