### ISSUE TITLE
The wheel distribution of this package on pypi contains the requirement for enum34

### ISSUE THREAD

**Issue by arterrey** [apache/libcloud#1392]
## Summary

The wheel distribution of this package on pypi contains the requirement for enum34

## Detailed Information

enum34 appears to be dynamical included as a requirement in setup.py depending if your Python version is pre 3.4.

```
PY2_or_3_pre_34 = sys.version_info < (3, 4, 0)
# ...
if PY2_or_3_pre_34:
    INSTALL_REQUIREMENTS.append('typing')
    INSTALL_REQUIREMENTS.append('enum34')
```

The wheel package contains the requirement without any special qualifier. (I'm not even sure if it is possible to spec requirements in a wheel according to python version)

From METADATA
```
Requires-Python: >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, <4
Requires-Dist: requests (>=2.5.0)
Requires-Dist: typing
Requires-Dist: enum34
```

This does create a problem in `zc.buildout` style environments that are running newer python versions.

I think it is probably time to drop support for Python 3.3

**Comment by arterrey** [comment]
A breaking buildout example..

For the buildout.cfg:
```
[buildout]
parts = libcloud

[libcloud]
recipe = zc.recipe.egg
eggs = apache-libcloud
interpreter = py
```

```
$ python3 -m venv .
$ bin/python3 --version
Python 3.6.8
$ bin/pip install -U pip
...
Successfully installed pip-19.3.1
$ bin/pip install zc.buildout
...
Successfully installed zc.buildout-2.13.2
[adam@cloudstation al]$ bin/buildout 
Creating directory '/home/adam/tmp/al/eggs'.
Creating directory '/home/adam/tmp/al/parts'.
Creating directory '/home/adam/tmp/al/develop-eggs'.
Getting distribution for 'zc.recipe.egg>=2.0.6'.
Got zc.recipe.egg 2.0.7.
Installing libcloud.
Getting distribution for 'apache-libcloud'.
Got apache-libcloud 2.7.0.
Getting distribution for 'typing'.
Got typing 3.7.4.1.
Getting distribution for 'requests>=2.5.0'.
Got requests 2.22.0.
Getting distribution for 'enum34'.
Got enum34 1.1.6.
Getting distribution for 'urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1'.
Got urllib3 1.25.7.
Getting distribution for 'idna<2.9,>=2.5'.
Got idna 2.8.
Getting distribution for 'chardet<3.1.0,>=3.0.2'.
Got chardet 3.0.4.
Getting distribution for 'certifi>=2017.4.17'.
Got certifi 2019.11.28.
Generated interpreter '/home/adam/tmp/al/bin/py'.
$ bin/py
Traceback (most recent call last):
  File "bin/py", line 41, in <module>
    __import__("code").interact(banner="", local=globals())
  File "/usr/local/python3.6/lib/python3.6/code.py", line 9, in <module>
    import traceback
  File "/usr/local/python3.6/lib/python3.6/traceback.py", line 5, in <module>
    import linecache
  File "/usr/local/python3.6/lib/python3.6/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/local/python3.6/lib/python3.6/tokenize.py", line 33, in <module>
    import re
  File "/usr/local/python3.6/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```

**Comment by Kami** [comment]
@arterrey Thanks for reporting this.

I'm looking into a fix. I believe we will be able to utilize PEP 508 notation (https://www.python.org/dev/peps/pep-0508/#environment-markers).
