### ISSUE TITLE
DNSProviders cannot handle Certification Authority Authorization (CAA) records

### ISSUE THREAD

**Issue by doddo** [apache/libcloud#1463]
## Summary

Libcloud DNSProviders cannot handle Certification Authority Authorization (CAA) records

## Detailed Information

First I manage a dns zone with CAA records in it.

Reproducer:

```python
 #!/usr/bin/env python

from libcloud.dns.providers import get_driver as get_dns_driver
from libcloud.dns.types import Provider as DNSProvider

import os

cls = get_dns_driver(DNSProvider.GANDI_LIVE)
driver = cls(os.getenv('TOKEN'))

for zone in driver.list_zones():
  for record in zone.list_records():
    print(record)
```
Produces this issue:

```
./caa.py  
Traceback (most recent call last):
  File "./caa.py", line 12, in <module>
    for record in zone.list_records():
  File "/home/petter/caa/venv/lib/python3.8/site-packages/libcloud/dns/base.py", line 81, in list_records
    return self.driver.list_records(zone=self)
  File "/home/petter/caa/venv/lib/python3.8/site-packages/libcloud/dns/drivers/gandi_live.py", line 136, in list_records
    return self._to_records(records.object, zone)
  File "/home/petter/caa/venv/lib/python3.8/site-packages/libcloud/dns/drivers/gandi_live.py", line 434, in _to_records
    records += self._to_record(r, zone)
  File "/home/petter/caa/venv/lib/python3.8/site-packages/libcloud/dns/drivers/gandi_live.py", line 388, in _to_record
    record = self._to_record_sub(data, zone, rrset_value)
  File "/home/petter/caa/venv/lib/python3.8/site-packages/libcloud/dns/drivers/gandi_live.py", line 424, in _to_record_sub
    type=self._string_to_record_type(data['rrset_type']),
  File "/home/petter/caa/venv/lib/python3.8/site-packages/libcloud/dns/base.py", line 584, in _string_to_record_type
    record_type = getattr(RecordType, string)
```

And indeed, CAA record is missing from `RecordType` class. I don't know how much more work it'd be to add support for this one, aside from adding it to the RecordType class. Anyhow creating a bug report seemed to be a prudent first step.

**Comment by Kami** [comment]
Yeah, most likely just adding it to the base ``RecordType`` enum class + GANGI_LIVE (https://github.com/apache/libcloud/blob/trunk/libcloud/dns/drivers/gandi.py#L90) provider should do the trick.

But you might also need to utilize ``extra`` dictionary in case you want to manage all the tags (issue, issuewild, iodef).

For simplicity / ease of use, we should likely default ``tag`` to ``issue`` if only ``value`` is provided, but ``extra['tag']`` is not.

**Comment by Kami** [comment]
#1464 should do it.

I only tested and implemented it for the CloudFlare and Gandi Live driver.

Other drivers will likely also require some minor modifications to make them support CAA record type.

**Comment by doddo** [comment]
neat!
