### ISSUE TITLE
Creation of backup driver fails for EBS with region formatting issue

### ISSUE THREAD

**Issue by rohan2962** [apache/libcloud#1634]
## Summary

Creating an EBS backup driver fails with region formatting issue

## Detailed Information

apache-libcloud version 3.4.1 python 3.6

>>> cls = libcloud.get_driver(libcloud.DriverType.BACKUP, libcloud.DriverType.BACKUP.EBS)
>>> backup_driver = cls(constants.CONFIG["aws_access_key"], constants.CONFIG["aws_secret_key"], region="ap-south-1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/.local/lib/python3.6/site-packages/libcloud/backup/drivers/ebs.py", line 59, in __init__
    self.connection.host = HOST % (region)
TypeError: not all arguments converted during string formatting

Unlike other AWS drivers, EBS does not have specific driver type per region. I suspect this is causing the issue.

**Comment by Kami** [comment]
Thanks for reporting this issue.

I'm looking at the code and I wonder if / how this ever worked since that code seems incorrect and would throw on every instantiation.

**Comment by Kami** [comment]
I'm trying to fix the driver since I thought it may be an easy fix, but it looks like the driver was never really fully implemented and working.

I fixed the region issue, but it looks like there are many other issues as well:

> <?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>NoSuchVersion</Code><Message>The requested version (2015-10-01) of service ManagedProxyService does not exist</Message></Error></Errors><RequestID>14ec4ef4-54f9-461f-aede-717b828f4fbe</RequestID></Response>

I will push a branch with WIP changes, but as I said above, it likely needs much more work to get everything working.

**Comment by Kami** [comment]
With #1635, instantiating the driver and authenticating with the API now works, but I haven't tested much else and it's likely that other things are not working as well since we have no unit tests for this driver to verify the correctness.

**Comment by rohan2962** [comment]
Thanks for the quick response and fix. Meanwhile, I see volumes functionality in compute driver itself like list_volumes() etc. Was the development of the specific driver not covered as the functionality was available elsewhere? This is speculative. Can somebody comment on this? Is there other functionality in this driver that is not available under the compute EC2 driver?
